### ISSUE TITLE
Develop async mechanism to pull eligible and curated publications from the curation DB

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-deposition-backend#11]

**Comment by jstewart-ebi** [comment]
I propose to add code into the Curation app to call a REST endpoint in Deposition to add a newly imported publication into Curation. For initial load, I can either call a bulk-load endpoint, or create a class to ad-hoc push all publications from Curation into Deposition. 
Need POST /v1/publication to create new publication, PUT /v1/publication to update status change from Curation to Deposition.
I will create a new ticket to send status changes from Deposition to Curation.

**Comment by tudorgroza** [comment]
@jstewart-ebi - would prefer not to have a `POST` endpoint on publications as it may lead to consistency issues. My preference would be for the initial load to be done manually - via a DB-direct bulk import (which I can take care of) and then continue with a similar strategy during the first couple of months until we see how people use the application. Happy to create the `PUT` endpoint to update the publication status.

**Comment by tudorgroza** [comment]
Done. To be deployed.
