### ISSUE TITLE
Comments on DTOs

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#34]
PublicationDto 
- Change authors to first author

CorrespondingAuthorDto 
- I haven't heard this mentioned in the last week. Is this still a requirement and where is this information coming from, template or field in frontend app?

**Comment by tudorgroza** [comment]
@twhetzel - `correspondingAuthor` comes from the publication model I've seen in the curation app. Might not be needed - happy to remove it.

**Comment by twhetzel** [comment]
What publication model is that? It might be needed, there was talk of having a way to contact the summary stats submitter but have not heard that discussed again.

**Comment by tudorgroza** [comment]
The backend model in the curation app. Don't really see the connection between the one submitting the data and the corresponding author on the publication ...

**Comment by twhetzel** [comment]
There was a discussion to capture an additional contact to be able to automate a curation task when data is released, i.e. emailing the contact author to let them know their publication and SS if loaded are now released. Emailed with Jackie and this part isn't MVP so the Depo front and backend don't need to handle this yet.

As for an author marked as the corresponding author in the publication, I'm not aware if that's used anywhere and don't recall what table that is in the Curation data model. As long as it's not a field the frontend needs to capture, I don't have any further comments on it.

**Comment by tudorgroza** [comment]
@twhetzel - Done and deployed. See: http://193.62.54.159/backend/v1/publications

**Comment by tudorgroza** [comment]
No - it's String. But it doesn't really matter since this is going to be imported automatically from the other DB. Nobody will actually edit it.
