### ISSUE TITLE
Request getAllPublications endpoint

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#37]
Since the curators will be going to the Deposition app and will not necessarily have a PubMed in mind vs. an author might, the curators will need to be able to view all publications eligible for curation. These include those that have not been curated and those that have been published, but do not have any summary stats. I'm not sure if there is a requirement to return all publications from the GWAS catalog database since the intent of this list is as a starting point for a curator to find a publication to start curating.

**Comment by tudorgroza** [comment]
I'll add a paginated version tonight and try to align it to the HAL way of representing objects, so that you can tell me if it works for you.

**Comment by tudorgroza** [comment]
@twhetzel - this is done and deployed - see http://193.62.54.159/backend/v1/publications
I've also updated the documentation on the main page of the repo, as well as changed the `/v1/publications/{id}` endpoint to take a dual semantics - id vs. pmid.

**Comment by tudorgroza** [comment]
@twhetzel - added HATEOAS support for publications (built and deployed - see http://193.62.54.159/backend/v1/publications). Please let me know if this is what you need and if I should follow the same pattern everywhere.

**Comment by twhetzel** [comment]
Overall looks good other than the paging issue you mentioned yesterday. 

When there is real data, for "publicationDate" do you plan to still return the time and date?

**Comment by tudorgroza** [comment]
@simonjupp - can I please have a dump of 100 odd publications from the curation DB to import them into the deposition app and iron out anything else that needs to be aligned - including the date format? Thank you.

**Comment by simonjupp** [comment]
You can have it. I’m probably not the best person to get it for you this week. Trish or Daniel should be able to help
