### ISSUE TITLE
Provide an endpoint with GCSTs, traits, and sample descriptions 

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#40]
To be able to provide a customized template for users who want to submit SS for an already published study, the endpoint that is being created needs a list of GCSTs for the study. It looks like this needs to be added to the StudyDto.java and returned in the "Retrieve submission by ID" endpoint, not sure it's needed in others.

PS - actually given the current discussion on what "Retrieve submission by ID" should return I'm not sure if this is where GCSTs should be returned...

cc: @jstewart-ebi, @simonjupp

**Comment by twhetzel** [comment]
@twhetzel @jstewart-ebi provide full spec of what is needed

**Comment by twhetzel** [comment]
@tudorgroza the only information I have is that there is an endpoint from Daniel (/v1/templates) that can generate a pre-filled template and to create this pre-filled template the parameters needed are: 
- GCSTs
- reported traits
- sample descriptions

I'll need to call on endpoint provided from the backend app to provide this download.

**Comment by tudorgroza** [comment]
Got the email from Daniel but I don't understand how is this supposed to work. I'll add you to the email trail.

**Comment by twhetzel** [comment]
Please add me and Jon.
