### ISSUE TITLE
Paging using "links" is not working for "Retrieve all publications" endpoint

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#41]
Just to follow-up from the Slack conversation, paging is not working for the "Retrieve all publications" endpoint because in the endpoints in the "links" is missing "backend" in the URL.  

I've been able to use the "page" information in the response. Do you plan to keep the first page as `number: 0`?

**Comment by tudorgroza** [comment]
@twhetzel - yeah - I did mention that in my previous message to you. W.r.t. the first page - I cannot control that - it just happens.

**Comment by twhetzel** [comment]
No problem, I can work with 0 as the first page number.
