### ISSUE TITLE
When deleting file, "clear" data for submission

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#44]
There are cases where a submission may validate with the status VALID, but the content of the data is incorrect after the submitter sees the summary stats, e.g. number of studies, associations, and samples associated with the submission. In this case, the submitter should be able to re-upload a file. 

I see there is an endpoint to delete the file, but there isn't an endpoint to delete the data associated with a VALID submission. The data, but not the entire submission should also be able to be deleted so that the created submission remains and is empty similar to the STARTED stage. Let us know if there are any questions/concerns.

**Comment by tudorgroza** [comment]
Performing a `DELETE /v1/submissions/{id}/fileUploads/{id}` has the same effect. Is a new endpoint needed?

**Comment by twhetzel** [comment]
I've been using that one to delete a file, but the stats seem to be additive when I submit another VALID file.

**Comment by tudorgroza** [comment]
Submitting a second file - or submitting a file after deleting the previous one?

**Comment by twhetzel** [comment]
Submitting a second valid file after deleting the previous submitted first valid file, e.g. submissionId 5d4052e7fc5fea0001269721

**Comment by tudorgroza** [comment]
Ook ... that's a bug :) I'll fix that. Should I still add a new endpoint?

**Comment by twhetzel** [comment]
The example submissionId I gave before is not a good example, but have seen this now consistently. If deleting the file `DELETE /v1/submissions/{submissionId}/uploads/{fileUploadId}` will also delete the data for that submission then that is all that is needed :)

**Comment by tudorgroza** [comment]
Great! Will fix it.

**Comment by twhetzel** [comment]
When you clear the data, will the status for the publication go back to `STARTED`?

**Comment by tudorgroza** [comment]
Yeah.

**Comment by tudorgroza** [comment]
Fixed deployed.

**Comment by twhetzel** [comment]
Works great!
