### ISSUE TITLE
Search submissions by PMID

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#48]
I am currently using the "Retrieve Submission by ID" to filter the table of submissions, however the submission Id is not the most intuitive to use for users. As a feature request, is it possible/easy to add a feature to allow search of submissions by PMID?  If there are other options to have the same effect, open to ideas.

**Comment by tudorgroza** [comment]
In Production, the list of submissions will be specific to the logged user - hence no filtering will be needed. Happy to add the endpoint if you want to though.

**Comment by twhetzel** [comment]
I'm not sure how many submissions a curator may be managing at any given time, but will double-check this feature is still of interest for curators.

**Comment by tudorgroza** [comment]
Implemented. Will deploy it tomorrow.
Endpoint is: `/v1/submissions?pmid=<PMID>` where `pmid` is optional.

**Comment by tudorgroza** [comment]
Deployed.
