### ISSUE TITLE
Summary statistics spreadsheet with incorrect URLs did not fail validation as it should

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-deposition-backend#58]
During curator testing, Eliot submitted a summary stats file with incorrect urls ("hello.txt"), validation failed, but did not change submission state to VALIDATION_FAILED. 
http://193.62.54.159/backend/v1/submissions/5d777e1148becc0001b42a4f
Validation failure needs to update validation status for submission.

**Comment by tudorgroza** [comment]
Notes to self:
 * Background publication: `5d77736c48becc0001b429e9`
 * Replaced for the time being with: http://193.62.54.159/deposition/submission/5d7b966c53ee1900019738da - which is now invalid because SS service is down (so at least this scenario is tested)
