### ISSUE TITLE
Duplicated error message and wrong submission status for an Invalid Summary stats file upload

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-backend#65]
The upload for http://193.62.54.159/backend/v1/submissions/5d8b582d26dcf30001a9c891  displays the error message repeated and an incorrect submission status, it shows validating vs. invalid. The uploaded file can be downloaded from here: http://193.62.54.159/deposition/submission/5d8b582d26dcf30001a9c891

**Comment by tudorgroza** [comment]
Fixed, deployed and tested. Submission test: http://193.62.54.159/deposition/submission/5d90b21d441bf600016f9c87
